- hosts: server:workstation
  become: true
  pre_tasks:

- hosts: firewall
  roles:
    - firewall

- hosts: server
  become: true
  roles:
    - base
    - server

- hosts: workstation
  become: true
  roles:
    - base
    - workstation
