 - hosts: all
   become: true
   pre_tasks:

 - hosts: all
   become: true
   roles:
     - base

 - hosts: file_servers
   become: true
   roles:
     - file_servers

 - hosts: k3s_agents
   become: true
   roles:
     - k3s_agents

 - hosts: k3s_servers
   become: true
   roles:
     - k3s_servers

 - hosts: workstations_sari
   become: true
   roles:
     - workstations_sari

 - hosts: workstations_ville
   become: true
   roles:
     - workstations_ville
