- name: daemon_reload
  tags: system,system-setup,daemon-reload
  service:
    daemon_reload: true

- name: restart_unattended_upgrades
  tags: system,system-setup,unattended-upgrades
  service:
    name: unattended-upgrades.service
    state: restarted