- name: users | ansible | copy vault key
  tags: dotfiles,ansible,vault,vault-key,users
  copy:
    src: users/ansible/vault_key
    dest: /home/ansible/.vault_key
    owner: ansible
    group: ansible
    mode: 0600