- name: users | sari | set bitwarden snap to autostart
  tags: dotfiles,dotfiles-sari
  copy:
    src: bitwarden
    dest: /home/sari/snap
    owner: sari
    group: sari
    mode: 0664
  when: bitwarden is defined and bitwarden == "snap"

- name: users | sari | add block to .bashrc
  tags: dotfiles,dotfiles-sari
  blockinfile:
    path: /home/sari/.bashrc
    insertafter: ""
    block: |
      # use bitwarden ssh agent
      SSH_AUTH_SOCK=/home/sari/snap/bitwarden/current/.bitwarden-ssh-agent.sock