- name: users | ville | copy personal config files
  tags: dotfiles,dotfiles-ville
  copy:
    src: users/ville/{{ item.src }}
    dest: /home/ville/{{ item.dest }}
    owner: ville
    group: ville
  with_items:
    - { src: 'layouts.json', dest: '.config/tiling-assistant/layouts.json' }
    - { src: 'waveterm', dest: 'snap' }

- name: users | ville | set brave as default browser
  tags: dotfiles,dotfiles-ville
  become_user: ville
  community.general.xdg_mime:
    mime_types:
      - text/html
      - x-scheme-handler/http
      - x-scheme-handler/https
      - application/xhtml+xml
    handler: brave_brave.desktop
  register: result

- name: users | ville | copy profile picture
  tags: dotfiles,dotfiles-ville
  copy:
    src: users/ville/profile_picture.png
    dest: /var/lib/AccountsService/icons/ville
    owner: root
    group: root
    mode: 0644
  when: main_user is defined and main_user == "ville"

- name: users | ville | set bitwarden snap to autostart
  tags: dotfiles,dotfiles-ville
  copy:
    src: bitwarden
    dest: /home/ville/snap
    owner: ville
    group: ville
    mode: 0664
  when: bitwarden is defined and bitwarden == "snap"

- name: users | ville | add block to .bashrc
  tags: dotfiles,dotfiles-ville
  blockinfile:
    path: /home/ville/.bashrc
    insertafter: ""
    block: |
      # upgrade command
      alias upgrade='sudo apt update && sudo apt upgrade && sudo snap refresh && sudo flatpak update'

      # use bitwarden ssh agent
      SSH_AUTH_SOCK=/home/ville/snap/bitwarden/current/.bitwarden-ssh-agent.sock