- name: users | ville | copy personal config files
  tags: dotfiles,dotfiles-ville
  copy:
    src: users/ville/{{ item.src }}
    dest: /home/ville/{{ item.dest }}
    owner: ville
    group: ville
  with_items:
    - { src: 'layouts.json', dest: '.config/tiling-assistant/layouts.json' }
    - { src: 'waveterm', dest: 'snap' }

- name: users | ville | set brave as default browser
  tags: dotfiles,dotfiles-ville
  become_user: ville
  community.general.gio_mime:
    mime_type: x-scheme-handler/https
    handler: brave_brave.desktop
  register: result

- name: users | ville | copy profile picture
  tags: dotfiles,dotfiles-ville
  copy:
    src: users/ville/profile_picture.png
    dest: /var/lib/AccountsService/icons/ville
    owner: root
    group: root
    mode: 0644
  when: main_user is defined and main_user == "ville"