- name: ansible setup | create ansible log file
  tags: ansible,ansible-setup
  file:
    path: /var/log/ansible.log
    owner: ansible
    group: ansible
    mode: 0664
    state: touch
  changed_when: False

- name: ansible setup | add logrotate config for ansible log file
  tags: ansible-setup
  copy:
    src: ansible_setup/logrotate
    dest: /etc/logrotate.d/ansible
    owner: root
    group: root
    mode: 0644

- name: ansible setup | generate provision script from template
  tags: ansible,ansible-setup,scripts
  template:
    src: provision.sh.j2
    dest: /usr/local/bin/provision
    owner: root
    group: root
    mode: 0755

- name: ansible setup | add unit file for systemd service
  tags: ansible,ansible-setup,systemd,service
  copy:
    src: ansible_setup/ansible.service
    dest: /etc/systemd/system/ansible.service
    owner: root
    group: root
    mode: 0644
  notify:
    - daemon_reload

- name: ansible setup | generate systemd timer from template
  tags: ansible,ansible-setup,systemd,timer
  template:
    src: ansible.timer.j2
    dest: /etc/systemd/system/ansible.timer
    owner: root
    group: root
    mode: 0644
  notify:
    - daemon_reload
    - restart_ansible_timer