- name: users | ville | copy personal config files
  tags: dotfiles,dotfiles-ville
  copy:
    src: users/ville/{{ item.src }}
    dest: /home/ville/{{ item.dest }}
    owner: ville
    group: ville
  with_items:
    - { src: 'layouts.json', dest: '.config/tiling-assistant/layouts.json' }
    - { src: 'monitors.xml', dest: '.config/monitors.xml' }
    - { src: 'waveterm-settings.json', dest: 'snap/waveterm/current/.config/waveterm/settings.json' }

- name: users | ville | copy profile picture
  tags: dotfiles,dotfiles-ville
  copy:
    src: users/ville/profile_picture.png
    dest: /var/lib/AccountsService/icons/ville
    owner: root
    group: root
    mode: 0644