- name: users | ansible | create user
  tags: ansible,sudo,users
  user:
    name: ansible
    system: yes

- name: users | ansible | add sudoers file
  tags: ansible,settings,simone,sudo,system,users
  copy:
    src: users/sudoers_ansible
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: 0440

- name: users | ansible | create .ssh directory
  tags: dotfiles,ansible,ssh,users
  file:
    path: "{{ item.dir }}"
    state: directory
    owner: ansible
    group: ansible
    mode: 0700
  with_items:
    - { dir: '/home/ansible/.ssh' }

- name: users | ansible | add public key
  tags: dotfiles,ansible,ssh,ssh-keys,users
  authorized_key:
    user: ansible
    key: "{{ item }}"
  with_file:
    - users/ansible/ansible.pub