- name: users | ville | add public key
  tags: dotfiles,ville,ssh,ssh-keys,users
  authorized_key:
    user: ville
    key: "{{ item }}"
  with_file:
    - users/ville/id_ed25519.pub
  when: ssh is defined and ssh == true