- name: system setup | fstab | create nextcloud directories
  tags: system,system-setup,fstab
  file:
    path: /home/{{ main_user }}/Nextcloud/{{ item.dir }}
    state: directory
    owner: "{{ main_user }}"
    group: "{{ main_user }}"
    mode: 0775
  with_items:
    - { dir: "{{ documents_dir }}" }
    - { dir: "{{ pictures_dir }}" }

- name: system setup | fstab | mount nextcloud directories
  tags: system,system-setup,fstab
  ansible.posix.mount:
    src: /home/{{ main_user }}/Nextcloud/{{ item }}
    path: /home/{{ main_user }}/{{ item }}
    fstype: none
    opts: bind
    state: mounted
  loop:
    - "{{ documents_dir }}"
    - "{{ pictures_dir }}"
  when: documents_dir is defined and pictures_dir is defined