- name: system setup | fstab | mount nextcloud directories
  tags: system,system-setup,fstab
  ansible.posix.mount:
    src: /home/{{ main_user }}/Nextcloud/{{ item }}
    path: /home/{{ main_user }}/{{ item }}
    fstype: none
    opts: bind
    state: mounted
  loop:
    - "{{ documents_dir }}"
    - "{{ pictures_dir }}"
  when: documents_dir is defined and pictures_dir is defined