- name: system setup | unattended upgrades | enable regular updates
  tags: system,system-setup,unattended-upgrades
  lineinfile:
      dest: /etc/apt/apt.conf.d/50unattended-upgrades
      regexp: '\/{0,2}\t"\$\{distro_id\}:\$\{distro_codename\}-updates";'
      line: '        "${distro_id}:${distro_codename}-updates";'
  notify: restart_unattended_upgrades

- name: system setup | unattended upgrades | remove unused dependencies
  tags: system,system-setup,unattended-upgrades
  lineinfile:
      dest: /etc/apt/apt.conf.d/50unattended-upgrades
      regexp: '\/\/Unattended-Upgrade::Remove-Unused-Dependencies "false";'
      line: 'Unattended-Upgrade::Remove-Unused-Dependencies "true";'
  notify: restart_unattended_upgrades

- name: system setup | unattended upgrades | enable on battery power
  tags: system,system-setup,unattended-upgrades
  lineinfile:
      dest: /etc/apt/apt.conf.d/50unattended-upgrades
      regexp: '\/\/ Unattended-Upgrade::OnlyOnACPower "true";'
      line: 'Unattended-Upgrade::OnlyOnACPower "false";'
  notify: restart_unattended_upgrades

- name: system setup | unattended upgrades | copy service files
  tags: system,system-setup,unattended-upgrades
  copy:
    src: unattended-upgrades/{{ item.src }}
    dest: /etc/systemd/system/{{ item.dest }}
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: 'apt-daily-upgrade.service', dest: 'apt-daily-upgrade.service' }
    - { src: 'apt-daily.service', dest: 'apt-daily.service' }
  notify:
    - daemon_reload
    - restart_unattended_upgrades

- name: system setup | unattended upgrades | generate timers from templates
  tags: system,system-setup,unattended-upgrades
  template:
    src: unattended-upgrades/{{ item.src }}
    dest: /etc/systemd/system/{{ item.dest }}
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: 'apt-daily-upgrade_timer.j2', dest: 'apt-daily-upgrade.timer' }
    - { src: 'apt-daily_timer.j2', dest: 'apt-daily.timer' }
  notify:
    - daemon_reload
    - restart_unattended_upgrades