- name: system setup | SRV rules | Deny SRV to SRV pfSenseAdmin
  tags: system,system-setup,rules,rules-srv
  pfsensible.core.pfsense_rule:
    action: block
    disabled: false
    interface: SRV
    ipprotocol: inet
    protocol: tcp/udp
    source: NET:SRV
    destination: IP:SRV
    destination_port: pfSenseAdmin
    name: Deny SRV to SRV pfSenseAdmin

- name: system setup | SRV rules | Deny SRV to NetbootXYZ Ports
  tags: system,system-setup,rules,rules-srv
  pfsensible.core.pfsense_rule:
    action: block
    disabled: false
    interface: SRV
    ipprotocol: inet
    protocol: tcp
    source: NET:SRV
    destination: NetbootXYZ
    destination_port: NetbootXYZports
    name: Deny SRV to NetbootXYZ Ports
    after: Deny SRV to SRV pfSenseAdmin

- name: system setup | SRV rules | Allow traffic inside SRV
  tags: system,system-setup,rules,rules-srv
  pfsensible.core.pfsense_rule:
    action: pass
    disabled: false
    interface: SRV
    ipprotocol: inet
    protocol: any
    source: NET:SRV
    destination: NET:SRV
    name: Allow traffic inside SRV
    after: Deny SRV to NetbootXYZ Ports

- name: system setup | SRV rules | Deny SRV to NAS pfSenseAdmin
  tags: system,system-setup,rules,rules-srv
  pfsensible.core.pfsense_rule:
    action: block
    disabled: false
    interface: SRV
    ipprotocol: inet
    protocol: tcp/udp
    source: NET:SRV
    destination: IP:NAS
    destination_port: pfSenseAdmin
    name: Deny SRV to NAS pfSenseAdmin
    after: Allow traffic inside SRV

- name: system setup | SRV rules | Allow SRV to NAS
  tags: system,system-setup,rules,rules-srv
  pfsensible.core.pfsense_rule:
    action: pass
    disabled: false
    interface: SRV
    ipprotocol: inet
    protocol: any
    source: NET:SRV
    destination: NET:NAS
    name: Allow SRV to NAS
    after: Deny SRV to NAS pfSenseAdmin

- name: system setup | SRV rules | Allow SRV to m600-server-1
  tags: system,system-setup,rules,rules-srv
  pfsensible.core.pfsense_rule:
    action: pass
    disabled: false
    interface: SRV
    ipprotocol: inet
    protocol: tcp/udp
    source: NET:SRV
    destination: m600server1
    destination_port: 22
    name: Allow SRV to m600-server-1
    after: Allow SRV to NAS

- name: system setup | SRV rules | Allow netboot.xyz to PERSONAL
  tags: system,system-setup,rules,rules-srv
  pfsensible.core.pfsense_rule:
    action: pass
    disabled: false
    interface: SRV
    ipprotocol: inet
    protocol: udp
    source: NetbootXYZ
    destination: NET:PERSONAL
    name: Allow netboot.xyz to PERSONAL
    after: Allow SRV to m600-server-1

- name: system setup | SRV rules | Allow SRV to non private networks
  tags: system,system-setup,rules,rules-srv
  pfsensible.core.pfsense_rule:
    action: pass
    disabled: false
    interface: SRV
    ipprotocol: inet
    protocol: any
    source: NET:SRV
    destination: "!PrivateNetworks"
    name: Allow SRV to non private networks
    after: Allow netboot.xyz to PERSONAL

- name: system setup | SRV rules | Allow SRV IPv6 to non private networks
  tags: system,system-setup,rules,rules-srv
  pfsensible.core.pfsense_rule:
    action: pass
    disabled: false
    interface: SRV
    ipprotocol: inet6
    protocol: any
    source: NET:SRV
    destination: "!PrivateNetworks6"
    name: Allow SRV IPv6 to non private networks
    after: Allow SRV to non private networks