# Load variables
- include_vars: 'mac-addresses.yml'
  tags: always

- block:
    # install software
    - import_tasks: software/packages.yml

    ## system setup
    - import_tasks: system_setup/setup.yml
    - import_tasks: system_setup/vlans.yml
    - import_tasks: system_setup/interfaces.yml
    - import_tasks: system_setup/dhcp.yml
    - import_tasks: system_setup/aliases.yml
    - import_tasks: system_setup/routes.yml