- name: software | bitwarden | install flatpak
  tags: packages,flatpak,bitwarden,workstation-packages
  flatpak:
    name: com.bitwarden.desktop
    state: present
  when: bitwarden is defined and bitwarden == "flatpak"

- name: software | bitwarden | install snap
  tags: packages,snap,bitwarden,workstation-packages
  snap:
    name: bitwarden
    state: present
  when: bitwarden is defined and bitwarden == "snap"

- name: software | bitwarden | connect to password-manager-service
  tags: packages,snap,bitwarden,workstation-packages
  ansible.builtin.command: sudo snap connect bitwarden:password-manager-service
