- name: software | jellyfin_desktop | install package
  tags: packages,flatpak,jellyfin_desktop,workstation-packages
  flatpak:
    name: org.jellyfin.JellyfinDesktop
    state: present
  when: jellyfin_desktop is defined and jellyfin_desktop == true