- name: software | spotify | install flatpak
  tags: packages,flatpak,spotify,workstation-packages
  flatpak:
    name: com.spotify.Client
    state: present
  when: spotify is defined and spotify == "flatpak"

- name: software | spotify | install snap
  tags: packages,snap,spotify,workstation-packages
  snap:
    name: spotify
    state: present
  when: spotify is defined and spotify == "snap"