- name: software | waveterm | install package
  tags: packages,waveterm,snap,workstation-packages
  snap:
    name: waveterm
    classic: true
    state: present
  when: waveterm is defined and waveterm == true