- name: software | spotify | install package
  tags: packages,flatpak,spotify,workstation-packages
  flatpak:
    name: com.spotify.Client
    state: present
  when: spotify_flatpak is defined and spotify_flatpak == true

- name: software | spotify | install package
  tags: packages,snap,spotify,workstation-packages
  snap:
    name: spotify
    state: present
  when: spotify_snap is defined and spotify_snap == true