- name: software | docker | set up docker apt repository
  tags: packages,docker,server-packages
  deb822_repository:
    name: docker
    types: deb
    uris: https://download.docker.com/linux/ubuntu
    suites: '{{ ansible_facts["distribution_release"] }}'
    components: stable
    architectures: amd64
    signed_by: https://download.docker.com/linux/ubuntu/gpg

- name: software | docker | install docker packages
  tags: packages,docker,server-packages
  ansible.builtin.apt:
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin
    update_cache: yes