- name: system setup | longhorn | install required packages
  tags: system,system-setup,longhorn,nfs-common
  package:
    name:
      - nfs-common
      - cryptsetup
      - dmsetup
      - open-iscsi
    state: present

- name: system setup | longhorn | stop and disable multipathd.service
  tags: system,system-setup,longhorn,multipathd
  service:
    name: multipathd.service
    state: stopped
    enabled: false

- name: system setup | longhorn | stop and disable multipathd.socket
  tags: system,system-setup,longhorn,multipathd
  service:
    name: multipathd.socket
    state: stopped
    enabled: false
