- name: system setup | unattended upgrades | enable regular updates
  tags: system,system-setup,unattended-upgrades
  lineinfile:
      dest: /etc/apt/apt.conf.d/50unattended-upgrades
      regexp: '\/{0,2}\t"\$\{distro_id\}:\$\{distro_codename\}-updates";'
      line: '        "${distro_id}:${distro_codename}-updates";'
  notify: restart_unattended_upgrades

- name: system setup | unattended upgrades | remove unused dependencies
  tags: system,system-setup,unattended-upgrades
  lineinfile:
      dest: /etc/apt/apt.conf.d/50unattended-upgrades
      regexp: '\/\/Unattended-Upgrade::Remove-Unused-Dependencies "false";'
      line: 'Unattended-Upgrade::Remove-Unused-Dependencies "true";'
  notify: restart_unattended_upgrades

- name: system setup | unattended upgrades | enable automatic reboot
  tags: system,system-setup,unattended-upgrades
  lineinfile:
      dest: /etc/apt/apt.conf.d/50unattended-upgrades
      regexp: '\/\/Unattended-Upgrade::Automatic-Reboot "false";'
      line: 'Unattended-Upgrade::Automatic-Reboot "true";'
  notify: restart_unattended_upgrades

- name: system setup | unattended upgrades | generate apt-daily-upgrade.timer from template
  tags: system,system-setup,unattended-upgrades
  template:
    src: apt-daily-upgrade_timer.j2
    dest: /etc/systemd/system/apt-daily-upgrade.timer
    owner: root
    group: root
    mode: 0644
  when: upgrade_time is defined
  notify:
    - daemon_reload
    - restart_unattended_upgrades