- name: system setup | wireguard | generate wg0.conf from template
  tags: system,system-setup,wireguard
  template:
    src: wg0_conf.j2
    dest: /etc/wireguard/wg0.conf
    owner: root
    group: root
    mode: 0600
  notify:
    - restart_wg-quick
