- name: system setup | install packages
  tags: system,packages
  package:
    state: present
    name:
      - pfSense-pkg-acme
      - pfSense-pkg-haproxy
      - pfSense-pkg-pfBlockerNG-devel
      - pfSense-pkg-sudo
      - pfSense-pkg-System_Patches
      - pfSense-pkg-WireGuard