- name: system setup | logind | HandleSuspendKey
  tags: system,system-setup,logind
  lineinfile:
      dest: /etc/systemd/logind.conf
      regexp: "#HandleSuspendKey=suspend"
      line: "HandleSuspendKey=suspend-then-hibernate"

- name: system setup | logind | HandleLidSwitch
  tags: system,system-setup,logind
  lineinfile:
      dest: /etc/systemd/logind.conf
      regexp: "#HandleLidSwitch=suspend"
      line: "HandleLidSwitch=suspend-then-hibernate"

- name: system setup | logind | HandleLidSwitchExternalPower
  tags: system,system-setup,logind
  lineinfile:
      dest: /etc/systemd/logind.conf
      regexp: "#HandleLidSwitchExternalPower=suspend"
      line: "HandleLidSwitchExternalPower=suspend-then-hibernate"

- name: system setup | logind | IdleAction
  tags: system,system-setup,logind
  lineinfile:
      dest: /etc/systemd/logind.conf
      regexp: "#IdleAction=ignore"
      line: "IdleAction=suspend-then-hibernate"