# Load host-specific variables
- include_vars: '{{ ansible_facts["hostname"] }}.yml'
  tags: always
  when: host_vars is defined and host_vars == true
- include_vars: 'k3s.yml'
  tags: always
  when: k3s is defined

- block:
    ## system setup
    - include_tasks: system_setup/ddclient.yml
      when: ddclient is defined and ddclient == true
    - include_tasks: system_setup/docker.yml
      when: docker is defined and docker == true
    - include_tasks: system_setup/k3s.yml
      when: k3s is defined
    - include_tasks: system_setup/logind_conf.yml
      when: laptop is defined and laptop == true
    - include_tasks: system_setup/longhorn.yml
      when: k3s is defined
    - import_tasks: system_setup/unattended_upgrades.yml
    - include_tasks: system_setup/wireguard.yml
      when: wireguard is defined and wireguard == true

    ## User configs
    - import_tasks: users/ansible.yml
    - import_tasks: users/ville.yml

    ## install software
    - include_tasks: software/docker.yml
      when: docker is defined and docker == true
    - import_tasks: software/ddclient.yml
    - import_tasks: software/wireguard.yml