# Load host-specific variables
- include_vars: "{{ ansible_hostname }}.yml"
  tags: always
  when: host_vars is defined and host_vars == true

- block:
    ## system setup
    - include_tasks: system_setup/ddclient.yml
      when: ddclient is defined and ddclient == true
    - include_tasks: system_setup/k3s.yml
      when: k3s is defined
    - import_tasks: system_setup/unattended_upgrades.yml
    - include_tasks: system_setup/wireguard.yml
      when: wireguard is defined and wireguard == true

    ## install software
    - import_tasks: software/ddclient.yml
    - import_tasks: software/wireguard.yml