- name: gnome | shell settings | color-scheme
  tags: gnome,gnome-shell
  become_user: ville
  dconf:
    key: "/org/gnome/desktop/interface/color-scheme"
    value: "'prefer-dark'"

- name: gnome | shell settings | show-battery-percentage
  tags: gnome,gnome-shell
  become_user: ville
  dconf:
    key: "/org/gnome/desktop/interface/show-battery-percentage"
    value: "true"

- name: gnome | shell settings | favorite-apps
  tags: gnome,gnome-shell
  become_user: ville
  dconf:
    key: "/org/gnome/shell/favorite-apps"
    value: >-
      ['brave_brave.desktop', 'thunderbird_thunderbird.desktop', 'waveterm_waveterm.desktop',
      'codium_codium.desktop', 'spotify_spotify.desktop', 'org.gnome.Nautilus.desktop',
      'org.gnome.Software.desktop', 'org.gnome.Yelp.desktop']

- name: gnome | shell settings | dash-max-icon-size
  tags: gnome,gnome-shell
  become_user: ville
  dconf:
    key: "/org/gnome/shell/extensions/dash-to-dock/dash-max-icon-size"
    value: "48"

- name: gnome | shell settings | dock-fixed
  tags: gnome,gnome-shell
  become_user: ville
  dconf:
    key: "/org/gnome/shell/extensions/dash-to-dock/dock-fixed"
    value: "false"

- name: gnome | shell settings | dock-position
  tags: gnome,gnome-shell
  become_user: ville
  dconf:
    key: "/org/gnome/shell/extensions/dash-to-dock/dock-position"
    value: "'LEFT'"

- name: gnome | shell settings | extend-height
  tags: gnome,gnome-shell
  become_user: ville
  dconf:
    key: "/org/gnome/shell/extensions/dash-to-dock/extend-height"
    value: "true"

- name: gnome | shell settings | show-mounts
  tags: gnome,gnome-shell
  become_user: ville
  dconf:
    key: "/org/gnome/shell/extensions/dash-to-dock/show-mounts"
    value: "false"

- name: gnome | shell settings | show-trash
  tags: gnome,gnome-shell
  become_user: ville
  dconf:
    key: "/org/gnome/shell/extensions/dash-to-dock/show-trash"
    value: "false"

- name: gnome | shell settings | startup-sound
  tags: gnome,gnome-shell
  become_user: ville
  dconf:
    key: "/org/gnome/shell/extensions/dash-to-dock/startup-sound"
    value: "'warty-startup'"