- name: daemon_reload
  tags: system,system-setup,daemon-reload
  service:
    daemon_reload: true

- name: restart_ansible_timer
  tags: ansible,ansible-setup,systemd,timer
  service:
    name: ansible.timer
    state: reloaded
    enabled: true

- name: restart_systemd_logind
  tags: system,system-setup,logind
  ansible.builtin.debug:
    msg: >-
      Systemd logind configuration file has changed, a relogin is required for the canges
      to take effect.

- name: restart_unattended_upgrades
  tags: system,system-setup,unattended-upgrades
  service:
    name: unattended-upgrades.service
    state: restarted

- name: update_grub
  tags: system,system-setup,update-grub
  command:
    cmd: "update-grub"