# Load distro-specific variables
- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- block:
    ## Configure swap
    - include_tasks: system_setup/swap.yml
      when: swap_size_mb is defined

    ## User configs
    - import_tasks: users/ville.yml
    - import_tasks: users/ansible.yml

    ## system setup
    - import_tasks: system_setup/clock.yml
    - import_tasks: system_setup/openssh.yml
      when: ssh is defined and ssh == true